# fry 0dbd6544491d5d2a1ad8fa4ae7949b41e8b6a745
# Generated by fryweb, DO NOT EDIT THIS FILE!
from fastapi import FastAPI
from fryweb import Element, html

app = FastAPI()

@app.get('/')
async def index():
    return html(App, autoreload=False)

def App():
    data = '<script>这是脚本</script>'
    return Element("div", {"call-client-script": ["app_App", [("data", data)]], "children": [Element("div", {"children": [Element("span", {"*": Element.ClientEmbed(0), "children": [f"这是一个&lt;strong&gt;text嵌入&lt;/strong&gt;"]})]}), Element("div", {"!": Element.ClientEmbed(1), "children": [f"""这是一个<strong>html嵌入</strong>"""]}), Element("div", {"children": [Element("p", {"children": ["hello world"]})]})]})